# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:37:45+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from starlette.requests import Request

from models import (
    ApiKey,
    ApiSecret,
    CheckFormatPostResponse,
    ControlFormatPostResponse,
    ErrorThrottled,
    FieldFormatPostResponse,
    Format,
    NetworkUnblock,
    NetworkUnblockPostResponse,
    NetworkUnblockResponseForbidden,
    NetworkUnblockResponseNotFound,
    NetworkUnblockResponseOk,
    Psd2FormatPostResponse,
    RequestIds,
    SearchFormatGetResponse,
)

app = MCPProxy(
    contact={
        'email': 'devrel@vonage.com',
        'name': 'Vonage DevRel',
        'url': 'https://developer.nexmo.com/',
    },
    description='The Verify API helps you to implement 2FA (two-factor authentication) in your applications. This is useful for:\n\n* Protecting against spam, by preventing spammers from creating multiple accounts\n* Monitoring suspicious activity, by forcing an account user to verify ownership of a number\n* Ensuring that you can reach your users at any time because you have their correct phone number\nMore information is available at <https://developer.nexmo.com/verify>',
    license={
        'name': 'The MIT License (MIT)',
        'url': 'https://opensource.org/licenses/MIT',
    },
    termsOfService='https://www.nexmo.com/terms-of-use',
    title='Verify API',
    version='1.2.4',
    servers=[{'url': 'https://api.nexmo.com/verify'}],
)


@app.post(
    '/check/{format}',
    description=""" Use Verify check to confirm that the PIN you received from your user matches the one sent by Vonage in your Verify request.

1. Send the verification `code` that your user supplied, with the corresponding `request_id` from the Verify request.
2. Check the `status` of the response to determine if the code the user supplied matches the one sent by Vonage.

*Note that this endpoint is available by `GET` request as well as `POST`.* """,
    tags=['verification_processes'],
)
def verify_check(format: Format, request: Request = ...):
    """
    Verify Check
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/control/{format}',
    description=""" Control the progress of your Verify requests. To cancel an existing Verify request, or to trigger the next verification event:


1. Send a Verify control request with the appropriate command (`cmd`) for what you want to achieve.

2. Check the `status` in the response.


*Note that this endpoint is available by `GET` request as well as `POST`.* """,
    tags=['verification_processes'],
)
def verify_control(format: Format, request: Request = ...):
    """
    Verify Control
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/network-unblock',
    description=""" Request to unblock a network that has been blocked due to potential fraud detection
<div class="Vlt-callout Vlt-callout--critical">
  <div class="Vlt-callout__content">
    <h4>Network Unblock is switched off by default.</h4>
    Please contact Sales to enable the Network Unblock API for your account.
  </div>
</div> """,
    tags=['network_access_control'],
)
def network_unblock(body: NetworkUnblock):
    """
    Request a network unblock
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/psd2/{format}',
    description=""" Use Verify request to generate and send a PIN to your user to authorize a payment:
1. Create a request to send a verification code to your user.
2. Check the `status` field in the response to ensure that your request was successful (zero is success).
3. Use the `request_id` field in the response for the Verify check.
(Please note that XML format is not supported for the Payment Services Directive endpoint at this time.) """,
    tags=['verification_processes'],
)
def verify_request_with_p_s_d2(format: Format, request: Request = ...):
    """
    PSD2 (Payment Services Directive 2) Request
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/search/{format}',
    description=""" Use Verify search to check the status of past or current verification requests:

1. Send a Verify search request containing the `request_id`s of the verification requests you are interested in.
2. Use the `status` of each verification request in the `checks` array of the response object to determine the outcome.

*Note that this endpoint is available by `POST` request as well as `GET`.* """,
    tags=['verification_processes'],
)
def verify_search(
    format: Format,
    api_key: ApiKey = ...,
    api_secret: ApiSecret = ...,
    request_id: str = ...,
    request_ids: Optional[RequestIds] = None,
):
    """
    Verify Search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/{format}',
    description=""" Use Verify request to generate and send a PIN to your user:

1. Create a request to send a verification code to your user.

2. Check the `status` field in the response to ensure that your request was successful (zero is success).

3. Use the `request_id` field in the response for the Verify check.

*Note that this endpoint is available by `GET` request as well as `POST`.* """,
    tags=['verification_processes'],
)
def verify_request(format: Format, request: Request = ...):
    """
    Request a Verification
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
