# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:37:45+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field, RootModel, conint, constr


class ErrorThrottled(BaseModel):
    detail: str = Field(
        ...,
        description='Additional information about the error',
        examples=['Please wait, then retry your request'],
    )
    instance: str = Field(
        ...,
        description='Internal Trace ID',
        examples=['bf0ca0bf927b3b52e3cb03217e1a1ddf'],
    )
    title: str = Field(
        ..., description='Generic error message', examples=['Rate Limit Hit']
    )
    type: str = Field(
        ...,
        description='Link to error / remediation options',
        examples=['https://developer.vonage.com/api-errors/verify#rate-limit'],
    )


class ApiKey(RootModel[str]):
    root: str = Field(
        ...,
        description='You can find your API key in your [account dashboard](https://dashboard.nexmo.com)',
        examples=['abcd1234'],
    )


class ApiSecret(RootModel[str]):
    root: str = Field(
        ...,
        description='You can find your API secret in your [account dashboard](https://dashboard.nexmo.com)',
        examples=['Sup3rS3cr3t!!'],
    )


class Status(Enum):
    field_0 = '0'
    field_1 = '1'
    field_2 = '2'
    field_3 = '3'
    field_4 = '4'
    field_5 = '5'
    field_6 = '6'
    field_16 = '16'
    field_17 = '17'


class CheckErrorResponse(BaseModel):
    error_text: Optional[str] = Field(
        None,
        description='If the `status` is non-zero, this explains the error encountered.',
        examples=['The code inserted does not match the expected value'],
    )
    request_id: Optional[str] = Field(
        None,
        description='The `request_id` that you received in the response to the Verify request and used in the Verify check request.',
        examples=['abcdef0123456789abcdef0123456789'],
    )
    status: Optional[Status] = Field(
        None,
        description='Code | Text | Description\n-- | -- | --\n0 | Success | The request was successfully accepted by Vonage.\n1 | Throttled | You are trying to send more than the maximum of 30 requests per second.\n2 | Your request is incomplete and missing the mandatory parameter `$parameter` | The stated parameter is missing.\n3 | Invalid value for parameter `$parameter` | Invalid value for parameter. If you see Facility not allowed in the error text, check that you are using the correct Base URL in your request.\n4 | Invalid credentials were provided | The supplied API key or secret in the request is either invalid or disabled.\n5 | Internal Error | An error occurred processing this request in the Cloud Communications Platform.\n6 | The Vonage platform was unable to process this message for the following reason: `$reason` | The request could not be routed.\n16 | The code inserted does not match the expected value |\n17 | The wrong code was provided too many times | You can run Verify check on a specific `request_id` up to three times unless a new verification code is generated. If you check a request more than three times, it is set to FAILED and you cannot check it again.\n',
        examples=['16'],
    )


class CheckRequest(BaseModel):
    api_key: ApiKey
    api_secret: ApiSecret
    code: constr(min_length=4, max_length=6) = Field(
        ...,
        description='The verification code entered by your user.',
        examples=['1234'],
    )
    ip_address: Optional[str] = Field(
        None, description='(This field is no longer used)', examples=['123.0.0.255']
    )
    request_id: constr(max_length=32) = Field(
        ...,
        description='The Verify request to check. This is the `request_id` you received in the response to the Verify request.',
        examples=['abcdef0123456789abcdef0123456789'],
    )


class Status1(Enum):
    field_0 = '0'
    field_1 = '1'
    field_2 = '2'
    field_3 = '3'
    field_4 = '4'
    field_5 = '5'
    field_6 = '6'
    field_8 = '8'
    field_9 = '9'
    field_19 = '19'


class ControlErrorResponse(BaseModel):
    error_text: Optional[str] = Field(
        None,
        description='If the `status` is non-zero, this explains the error encountered.',
        examples=[
            "The requestId 'abcdef0123456789abcdef' does not exist or its no longer active."
        ],
    )
    status: Optional[Status1] = Field(
        None,
        description='Code | Text | Description\n-- | -- | --\n0 | Success | The request was successfully accepted by Vonage.\n1 | Throttled | You are trying to send more than the maximum of 30 requests per second.\n2 | Your request is incomplete and missing the mandatory parameter `$parameter` | The stated parameter is missing.\n3 | Invalid value for parameter `$parameter` | Invalid value for parameter. If you see Facility not allowed in the error text, check that you are using the correct Base URL in your request.\n4 | Invalid credentials were provided | The supplied API key or secret in the request is either invalid or disabled.\n5 | Internal Error | An error occurred processing this request in the Cloud Communications Platform.\n6 | The Vonage platform was unable to process this message for the following reason: `$reason` | The request could not be routed.\n8 | The api_key you supplied is for an account that has been barred from submitting messages. |\n9 | Partner quota exceeded | Your account does not have sufficient credit to process this request.\n19 | For `cancel`: Either you have not waited at least 30 secs after sending a Verify request before cancelling or Verify has made too many attempts to deliver the verification code for this request and you must now wait for the process to complete. For `trigger_next_event`: All attempts to deliver the verification code for this request have completed and there are no remaining events to advance to.\n',
        examples=['6'],
    )


class Cmd(Enum):
    cancel = 'cancel'
    trigger_next_event = 'trigger_next_event'


class ControlRequest(BaseModel):
    api_key: ApiKey
    api_secret: ApiSecret
    cmd: Cmd = Field(
        ...,
        description='The possible commands are `cancel` to request cancellation of the verification process, or `trigger_next_event` to advance  to the next verification event (if any). Cancellation is only possible 30 seconds after the start of the verification request and before the second event (either TTS or SMS) has taken place.',
        examples=['cancel'],
    )
    request_id: str = Field(
        ...,
        description='The `request_id` you received in the response to the Verify request.',
        examples=['abcdef0123456789abcdef0123456789'],
    )


class Command(Enum):
    cancel = 'cancel'
    trigger_next_event = 'trigger_next_event'


class ControlResponse(BaseModel):
    command: Optional[Command] = Field(
        None, description='The `cmd` you sent in the request.', examples=['cancel']
    )
    status: Optional[str] = Field(
        None,
        description='`cmd` | Code | Description\n-- | -- | --\nAny | 0 | Success\n',
        examples=['0'],
    )


class EstimatedPriceMessagesSent(RootModel[str]):
    root: str = Field(
        ...,
        description='This field may not be present, depending on your pricing model. The\nvalue indicates the cost (in EUR) of the calls made and messages sent\nfor the verification process. This value may be updated during and\nshortly after the request completes because user input events can\noverlap with message/call events. When this field is present, the total\ncost of the verification is the sum of this field and the `price` field.\n',
        examples=['0.03330000'],
    )


class NetworkUnblock(BaseModel):
    network: Optional[str] = Field(
        None, description='The Network code', examples=[32526]
    )
    unblock_duration: Optional[conint(ge=0, le=86400)] = Field(
        3600,
        description='An optional duration the unblock will be applied for in seconds',
        examples=['3600'],
    )


class NetworkUnblockResponseForbidden(BaseModel):
    detail: Optional[str] = Field(
        None,
        description='Verbose description of the server error.',
        examples=['Your account does not have permission to perform this action.'],
    )
    instance: Optional[str] = Field(
        None,
        description='The Instance ID',
        examples=['bf0ca0bf927b3b52e3cb03217e1a1ddf'],
    )
    title: Optional[str] = Field(
        None,
        description='Full string text of the HTTP error code.',
        examples=['Forbidden'],
    )
    type: Optional[str] = Field(
        None,
        description='A URL link to the API documentation for this type of error.',
        examples=['https://developer.vonage.com/api-errors#forbidden'],
    )


class InvalidParameter(BaseModel):
    name: Optional[str] = Field(
        None, description='The name of the parameter.', examples=['network']
    )
    reason: Optional[str] = Field(
        None,
        description='The reason for the parameter error.',
        examples=['Network not found'],
    )


class NetworkUnblockResponseInvalidDuration(BaseModel):
    detail: Optional[str] = Field(
        None,
        description='Verbose description of the server error.',
        examples=['Unblock duration is invalid.'],
    )
    instance: Optional[str] = Field(
        None,
        description='The Instance ID',
        examples=['bf0ca0bf927b3b52e3cb03217e1a1ddf'],
    )
    invalid_parameters: Optional[List[InvalidParameter]] = Field(
        None, description='Detailed payload of errors.'
    )
    title: Optional[str] = Field(
        None,
        description='Full string text of the HTTP error code.',
        examples=['Invalid unblock_duration parameter'],
    )
    type: Optional[str] = Field(
        None,
        description='A URL link to the API documentation for this type of error.',
        examples=['https://developer.vonage.com/api-errors#invalid-paramater'],
    )


class NetworkUnblockResponseNotFound(BaseModel):
    detail: Optional[str] = Field(
        None,
        description='Verbose description of the server error.',
        examples=['The network you provided does not have an active block.'],
    )
    instance: Optional[str] = Field(
        None, description='InstanceID', examples=['bf0ca0bf927b3b52e3cb03217e1a1ddf']
    )
    title: Optional[str] = Field(
        None,
        description='Full string text of the HTTP error code.',
        examples=['Not Found'],
    )
    type: Optional[str] = Field(
        None,
        description='A URL link to the API documentation for this type of error.',
        examples=['https://developer.vonage.com/api-errors#bad-request'],
    )


class NetworkUnblockResponseOk(BaseModel):
    network: Optional[str] = Field(
        None, description='The unique network ID', examples=['23410']
    )
    unblocked_until: Optional[str] = Field(
        None,
        description='Gives the DateTime when the unblock will expire.',
        examples=['2024-04-22T08:34:58Z'],
    )


class NetworkUnblockResponseUnprocessableNetwork(BaseModel):
    detail: Optional[str] = Field(
        None,
        description='Verbose description of the server error.',
        examples=['Network is not in the request.'],
    )
    instance: Optional[str] = Field(
        None,
        description='The Instance ID',
        examples=['bf0ca0bf927b3b52e3cb03217e1a1ddf'],
    )
    invalid_parameters: Optional[List[InvalidParameter]] = Field(
        None, description='Detailed payload of errors.'
    )
    title: Optional[str] = Field(
        None,
        description='Full string text of the HTTP error code.',
        examples=['Network not found.'],
    )
    type: Optional[str] = Field(
        None,
        description='A URL link to the API documentation for this type of error.',
        examples=['https://developer.vonage.com/api-errors#invalid-paramater'],
    )


class CodeLength(Enum):
    integer_4 = 4
    integer_6 = 6


class Lg(Enum):
    en_gb = 'en-gb'
    bg_bg = 'bg-bg'
    cs_cz = 'cs-cz'
    da_dk = 'da-dk'
    de_de = 'de-de'
    ee_et = 'ee-et'
    el_gr = 'el-gr'
    es_es = 'es-es'
    fi_fi = 'fi-fi'
    fr_fr = 'fr-fr'
    ga_ie = 'ga-ie'
    hu_hu = 'hu-hu'
    it_it = 'it-it'
    lv_lv = 'lv-lv'
    lt_lt = 'lt-lt'
    mt_mt = 'mt-mt'
    nl_nl = 'nl-nl'
    pl_pl = 'pl-pl'
    sk_sk = 'sk-sk'
    sl_si = 'sl-si'
    sv_se = 'sv-se'


class WorkflowId(Enum):
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4
    integer_5 = 5
    integer_6 = 6
    integer_7 = 7


class Psd2Request(BaseModel):
    amount: float = Field(
        ...,
        description='The decimal amount of the payment to be confirmed, in Euros',
        examples=['48.00'],
    )
    api_key: ApiKey
    api_secret: ApiSecret
    code_length: Optional[CodeLength] = Field(
        4, description='The length of the verification code.', examples=[6]
    )
    country: Optional[str] = Field(
        None,
        description='If you do not provide `number` in international format or you are not sure if `number` is correctly formatted, specify the two-character country code in `country`. Verify will then format the number for you.',
        examples=['GB'],
    )
    lg: Optional[Lg] = Field(
        'en-gb',
        description='By default, the SMS or text-to-speech (TTS) message is generated in the locale that matches the `number`. For example, the text message or TTS message for a `33*` number is sent in French. Use this parameter to explicitly control the language used.\n*Note: Voice calls in English for `bg-bg`, `ee-et`, `ga-ie`, `lv-lv`, `lt-lt`, `mt-mt`, `sk-sk`, `sk-si`',
        examples=['es-es'],
    )
    next_event_wait: Optional[conint(ge=60, le=900)] = Field(
        300,
        description='Specifies the wait time in seconds between attempts to deliver the verification code.',
        examples=[120],
    )
    number: str = Field(
        ...,
        description='The mobile or landline phone number to verify. Unless you are setting `country` explicitly, this number must be in [E.164](https://en.wikipedia.org/wiki/E.164) format.',
        examples=['447700900000'],
    )
    payee: constr(max_length=18) = Field(
        ...,
        description='An alphanumeric string to indicate to the user the name of the recipient that they are confirming a payment to.',
        examples=['Acme Inc'],
    )
    pin_expiry: Optional[conint(ge=60, le=3600)] = Field(
        300,
        description='How long the generated verification code is valid for, in seconds. When you specify both `pin_expiry` and `next_event_wait` then `pin_expiry` must be an integer multiple of `next_event_wait` otherwise `pin_expiry` is defaulted to equal next_event_wait. See [changing the event timings](https://developer.nexmo.com/verify/guides/changing-default-timings).',
        examples=[240],
    )
    workflow_id: Optional[WorkflowId] = Field(
        1,
        description='Selects the predefined sequence of SMS and TTS (Text To Speech) actions to use in order to convey the PIN to your user. For example, an id of 1 identifies the workflow SMS - TTS - TTS. For a list of all workflows and their associated ids, please visit the [developer portal](https://developer.nexmo.com/verify/guides/workflows-and-events).',
        examples=[4],
    )


class Status2(Enum):
    field_0 = '0'
    field_1 = '1'
    field_2 = '2'
    field_3 = '3'
    field_4 = '4'
    field_5 = '5'
    field_6 = '6'
    field_7 = '7'
    field_8 = '8'
    field_9 = '9'
    field_10 = '10'
    field_15 = '15'
    field_20 = '20'
    field_29 = '29'


class RequestErrorResponse(BaseModel):
    error_text: Optional[str] = Field(
        None,
        description='If `status` is non-zero, this explains the error encountered.',
        examples=[
            'Your request is incomplete and missing the mandatory parameter `number`'
        ],
    )
    network: Optional[str] = Field(
        None,
        description='The Network ID of the blocking network, if relevant to the error.',
        examples=['244523'],
    )
    request_id: Optional[constr(max_length=32)] = Field(
        None,
        description='The unique ID of the Verify request. This may be blank in an error situation.',
        examples=[''],
    )
    status: Optional[Status2] = Field(
        None,
        description='Code | Text | Description\n-- | -- | --\n0 | Success | The request was successfully accepted by Vonage.\n1 | Throttled | You are trying to send more than the maximum of 30 requests per second.\n2 | Your request is incomplete and missing the mandatory parameter `$parameter` | The stated parameter is missing.\n3 | Invalid value for parameter `$parameter` | Invalid value for parameter. If you see Facility not allowed in the error text, check that you are using the correct Base URL in your request.\n4 | Invalid credentials were provided | The supplied API key or secret in the request is either invalid or disabled.\n5 | Internal Error | An error occurred processing this request in the Cloud Communications Platform.\n6 | The Vonage platform was unable to process this message for the following reason: `$reason` | The request could not be routed.\n7 | The number you are trying to verify is blacklisted for verification. | Returns a `network` property but no `request_id` will be present in the response.\n8 | The api_key you supplied is for an account that has been barred from submitting messages. |\n9 | Partner quota exceeded | Your account does not have sufficient credit to process this request.\n10 | Concurrent verifications to the same number are not allowed. | This will return a `request_id`.\n15 | The destination number is not in a supported network | The request has been rejected. Find out more about this error in the [Knowledge Base](https://help.nexmo.com/hc/en-us/articles/360018406532-Verify-On-demand-Service-to-High-Risk-Countries)\n20 | This account does not support the parameter: pin_code. | Only certain accounts have the ability to set the `pin_code`. Please contact your account manager for more information.\n29 | Non-Permitted Destination | Your Vonage account is still in demo mode. While in demo mode you must add target numbers to the approved list for your account. Add funds to your account to remove this limitation.\n',
        examples=['2'],
    )


class RequestResponse(BaseModel):
    request_id: Optional[constr(max_length=32)] = Field(
        None,
        description='The unique ID of the Verify request. You need this `request_id` for the Verify check.',
        examples=['abcdef0123456789abcdef0123456789'],
    )
    status: Optional[str] = Field(
        None,
        description='Indicates the outcome of the request; zero is success',
        examples=['0'],
    )


class Status3(Enum):
    IN_PROGRESS = 'IN PROGRESS'
    FAILED = 'FAILED'
    EXPIRED = 'EXPIRED'
    CANCELLED = 'CANCELLED'
    field_101 = '101'


class SearchErrorResponse(BaseModel):
    error_text: Optional[str] = Field(
        None,
        description='If `status` is not `SUCCESS`, this message explains the issue encountered.',
        examples=['No response found'],
    )
    request_id: Optional[str] = Field(
        None,
        description='The `request_id` that you received in the response to the Verify request and used in the Verify search request. May be empty in an error situation.',
        examples=['abcdef0123456789abcdef0123456789'],
    )
    status: Optional[Status3] = Field(
        None,
        description='Code | Description\n-- | --\nIN PROGRESS | The search is still in progress.\nSUCCESS | Your user entered a correct verification code.\nFAILED | Your user entered an incorrect code more than three times.\nEXPIRED | Your user did not enter a code before the `pin_expiry` time elapsed.\nCANCELLED | The verification process was cancelled by a Verify control request.\n101 | You supplied an invalid `request_id`, or the data is not available. Note that for recently-completed requests, there can be a delay of up to 1 minute before the results are available in search.\n',
        examples=['IN PROGRESS'],
    )


class Status4(Enum):
    VALID = 'VALID'
    INVALID = 'INVALID'


class Check(BaseModel):
    code: Optional[str] = Field(
        None,
        description='The code supplied with this check request',
        examples=['987654'],
    )
    date_received: Optional[str] = Field(
        None,
        description='The date and time this check was received (in the format YYYY-MM-DD HH:MM:SS)',
        examples=['2020-01-01 12:00:00'],
    )
    ip_address: Optional[str] = Field(
        None,
        description='The IP address, if available (this field is no longer used).',
        examples=['123.0.0.255'],
    )
    status: Optional[Status4] = None


class Type(Enum):
    tts = 'tts'
    sms = 'sms'


class Event(BaseModel):
    id: Optional[str] = None
    type: Optional[Type] = None


class Status5(Enum):
    IN_PROGRESS = 'IN PROGRESS'
    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'
    EXPIRED = 'EXPIRED'
    CANCELLED = 'CANCELLED'


class SearchResponse(BaseModel):
    account_id: Optional[str] = Field(
        None,
        description='The Vonage account ID the request was for.',
        examples=['abcdef01'],
    )
    checks: Optional[List[Check]] = Field(
        None,
        description='The list of checks made for this verification and their outcomes.',
    )
    currency: Optional[str] = Field(
        None, description='The currency code.', examples=['EUR']
    )
    date_finalized: Optional[str] = Field(
        None,
        description='The date and time the verification request was completed. This response parameter is in the following format YYYY-MM-DD HH:MM:SS.',
        examples=['2020-01-01 12:00:00'],
    )
    date_submitted: Optional[str] = Field(
        None,
        description='The date and time the verification request was submitted, in the following format YYYY-MM-DD HH:MM:SS.',
        examples=['2020-01-01 12:00:00'],
    )
    estimated_price_messages_sent: Optional[EstimatedPriceMessagesSent] = None
    events: Optional[List[Event]] = Field(
        None,
        description='The events that have taken place to verify this number, and their unique identifiers.',
    )
    first_event_date: Optional[str] = Field(
        None,
        description='The time the first verification attempt was made, in the following format YYYY-MM-DD HH:MM:SS.',
        examples=['2020-01-01 12:00:00'],
    )
    last_event_date: Optional[str] = Field(
        None,
        description='The time the last verification attempt was made, in the following format YYYY-MM-DD HH:MM:SS.',
        examples=['2020-01-01 12:00:00'],
    )
    number: Optional[str] = Field(
        None,
        description='The phone number this verification request was used for.',
        examples=['447700900000'],
    )
    price: Optional[str] = Field(
        None,
        description='The cost incurred for this verification request.',
        examples=['0.10000000'],
    )
    request_id: Optional[str] = Field(
        None,
        description='The `request_id` that you received in the response to the Verify request and used in the Verify search request.',
        examples=['abcdef0123456789abcdef0123456789'],
    )
    sender_id: Optional[str] = Field(
        'verify',
        description='The `sender_id` you provided in the Verify request.',
        examples=['mySenderId'],
    )
    status: Optional[Status5] = Field(
        None,
        description='Code | Description\n-- | --\nIN PROGRESS | The search is still in progress.\nSUCCESS | Your user entered a correct verification code.\nFAILED | Your user entered an incorrect code more than three times.\nEXPIRED | Your user did not enter a code before the `pin_expiry` time elapsed.\nCANCELLED | The verification process was cancelled by a Verify control request.\n',
        examples=['IN PROGRESS'],
    )


class Lg1(Enum):
    ar_xa = 'ar-xa'
    cs_cz = 'cs-cz'
    cy_cy = 'cy-cy'
    cy_gb = 'cy-gb'
    da_dk = 'da-dk'
    de_de = 'de-de'
    el_gr = 'el-gr'
    en_au = 'en-au'
    en_gb = 'en-gb'
    en_in = 'en-in'
    en_us = 'en-us'
    es_es = 'es-es'
    es_mx = 'es-mx'
    es_us = 'es-us'
    fi_fi = 'fi-fi'
    fil_ph = 'fil-ph'
    fr_ca = 'fr-ca'
    fr_fr = 'fr-fr'
    hi_in = 'hi-in'
    hu_hu = 'hu-hu'
    id_id = 'id-id'
    is_is = 'is-is'
    it_it = 'it-it'
    ja_jp = 'ja-jp'
    ko_kr = 'ko-kr'
    nb_no = 'nb-no'
    nl_nl = 'nl-nl'
    pl_pl = 'pl-pl'
    pt_br = 'pt-br'
    pt_pt = 'pt-pt'
    ro_ro = 'ro-ro'
    ru_ru = 'ru-ru'
    sv_se = 'sv-se'
    th_th = 'th-th'
    tr_tr = 'tr-tr'
    vi_vn = 'vi-vn'
    yue_cn = 'yue-cn'
    zh_cn = 'zh-cn'
    zh_tw = 'zh-tw'


class VerifyRequest(BaseModel):
    api_key: ApiKey
    api_secret: ApiSecret
    brand: constr(max_length=18) = Field(
        ...,
        description='An 18-character alphanumeric string you can use to personalize the verification request SMS body, to help users identify your company or application name. For example: "Your `Acme Inc` PIN is ..."',
        examples=['Acme Inc'],
    )
    code_length: Optional[CodeLength] = Field(
        4, description='The length of the verification code.', examples=[6]
    )
    country: Optional[str] = Field(
        None,
        description='If you do not provide `number` in international format or you are not sure if `number` is correctly formatted, specify the two-character country code in `country`. Verify will then format the number for you.',
        examples=['GB'],
    )
    lg: Optional[Lg1] = Field(
        'en-us',
        description='By default, the SMS or text-to-speech (TTS) message is generated in the locale that matches the `number`. For example, the text message or TTS message for a `33*` number is sent in French. Use this parameter to explicitly control the language used for the Verify request. A list of languages is available: <https://developer.nexmo.com/verify/guides/verify-languages>',
        examples=['en-us'],
    )
    next_event_wait: Optional[conint(ge=60, le=900)] = Field(
        300,
        description='Specifies the wait time in seconds between attempts to deliver the verification code.',
        examples=[120],
    )
    number: str = Field(
        ...,
        description='The mobile or landline phone number to verify. Unless you are setting `country` explicitly, this number must be in [E.164](https://en.wikipedia.org/wiki/E.164) format.',
        examples=['447700900000'],
    )
    pin_code: Optional[str] = Field(
        None,
        description='A custom PIN to send to the user. If a PIN is not provided, Verify will generate a random PIN for you. <b>This feature is not enabled by default</b> - please discuss with your Account Manager if you would like it enabled. If this feature is not enabled on your account, error status `20` will be returned.',
        examples=['AKFG-3424'],
    )
    pin_expiry: Optional[conint(ge=60, le=3600)] = Field(
        300,
        description='How long the generated verification code is valid for, in seconds. When you specify both `pin_expiry` and `next_event_wait` then `pin_expiry` must be an integer multiple of `next_event_wait` otherwise `pin_expiry` is defaulted to equal next_event_wait. See [changing the event timings](https://developer.nexmo.com/verify/guides/changing-default-timings).',
        examples=[240],
    )
    sender_id: Optional[constr(max_length=11)] = Field(
        'VERIFY',
        description='An 11-character alphanumeric string that represents the [identity of the sender](https://developer.nexmo.com/messaging/sms/guides/custom-sender-id) of the verification request. Depending on the destination of the phone number you are sending the verification SMS to, restrictions might apply.',
        examples=['ACME'],
    )
    workflow_id: Optional[WorkflowId] = Field(
        1,
        description='Selects the predefined sequence of SMS and TTS (Text To Speech) actions to use in order to convey the PIN to your user. For example, an id of 1 identifies the workflow SMS - TTS - TTS. For a list of all workflows and their associated ids, please visit the [developer portal](https://developer.nexmo.com/verify/guides/workflows-and-events).',
        examples=[4],
    )


class Format(Enum):
    json = 'json'
    xml = 'xml'


class ControlFormatPostResponse(
    RootModel[Union[ControlResponse, ControlErrorResponse]]
):
    root: Union[ControlResponse, ControlErrorResponse]


class NetworkUnblockPostResponse(
    RootModel[
        Union[
            NetworkUnblockResponseUnprocessableNetwork,
            NetworkUnblockResponseInvalidDuration,
        ]
    ]
):
    root: Union[
        NetworkUnblockResponseUnprocessableNetwork,
        NetworkUnblockResponseInvalidDuration,
    ]


class Psd2FormatPostResponse(RootModel[Union[RequestResponse, RequestErrorResponse]]):
    root: Union[RequestResponse, RequestErrorResponse]


class SearchFormatGetResponse(RootModel[Union[SearchResponse, SearchErrorResponse]]):
    root: Union[SearchResponse, SearchErrorResponse]


class RequestIds(RootModel[List[str]]):
    root: List[str] = Field(..., max_length=10)


class FieldFormatPostResponse(RootModel[Union[RequestResponse, RequestErrorResponse]]):
    root: Union[RequestResponse, RequestErrorResponse]


class CheckResponse(BaseModel):
    currency: Optional[str] = Field(
        None, description='The currency code.', examples=['EUR']
    )
    estimated_price_messages_sent: Optional[EstimatedPriceMessagesSent] = None
    event_id: Optional[str] = Field(
        None,
        description='The ID of the verification event, such as an SMS or TTS call.',
        examples=['0A00000012345678'],
    )
    price: Optional[str] = Field(
        None, description='The cost incurred for this request.', examples=['0.10000000']
    )
    request_id: Optional[str] = Field(
        None,
        description='The `request_id` that you received in the response to the Verify request and used in the Verify check request.',
        examples=['abcdef0123456789abcdef0123456789'],
    )
    status: Optional[str] = Field(
        None,
        description='A value of `0` indicates that your user entered the correct code. If it is non-zero, check the `error_text`.',
        examples=['0'],
    )


class CheckFormatPostResponse(RootModel[Union[CheckResponse, CheckErrorResponse]]):
    root: Union[CheckResponse, CheckErrorResponse]
